"""Hand-drawn-style schematics for the CountingPhotons lectures.

Every diagram is generated by code, like every other figure in this course.
Usage inside a notebook (from the lectures/ directory):

    from sketches import qho_ladder
    qho_ladder()

On Google Colab (single-notebook mode) fetch this file first — see the
loader cell in the notebooks that use it.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import (Circle, FancyArrowPatch, Polygon,
                                Rectangle, Wedge)

INK = "#30343a"          # base line color, softer than pure black
ACCENT = "tab:blue"
HOT = "tab:red"
GOOD = "tab:green"


def _canvas(w=8.0, h=4.0):
    """Blank, axis-free canvas with equal aspect."""
    fig, ax = plt.subplots(figsize=(w, h))
    ax.set_aspect("equal")
    ax.axis("off")
    return fig, ax


def _beamsplitter(ax, x, y, size=0.5, label="BS"):
    """A beamsplitter cube with its diagonal, centered on (x, y)."""
    s = size / 2
    ax.add_patch(Rectangle((x - s, y - s), size, size, facecolor="#d9e6f2",
                           edgecolor=INK, lw=1.5, zorder=3))
    ax.plot([x - s, x + s], [y - s, y + s], color=INK, lw=1.5, zorder=4)
    if label:
        ax.text(x, y - s - 0.18, label, ha="center", va="top",
                fontsize=10, color=INK)


def _detector(ax, x, y, angle=0.0, label="D", color="#f2d9d9"):
    """Half-disc single-photon detector pointing along `angle` (deg)."""
    ax.add_patch(Wedge((x, y), 0.28, angle + 90, angle + 270,
                       facecolor=color, edgecolor=INK, lw=1.5, zorder=4))
    dx = 0.5 * np.cos(np.radians(angle))
    dy = 0.5 * np.sin(np.radians(angle))
    ax.text(x - dx * 1.1, y - dy * 1.1, label, ha="center", va="center",
            fontsize=10, color=INK)


def _beam(ax, x0, y0, x1, y1, color=ACCENT, lw=2.0, arrow=True, ls="-"):
    """A light path with an optional arrowhead."""
    if arrow:
        ax.add_patch(FancyArrowPatch((x0, y0), (x1, y1), lw=lw, color=color,
                                     linestyle=ls, arrowstyle="-|>",
                                     mutation_scale=14, zorder=2))
    else:
        ax.plot([x0, x1], [y0, y1], color=color, lw=lw, ls=ls, zorder=2)


def _photon(ax, x, y, color=HOT, r=0.07):
    """A photon: a filled dot with a short wave over it."""
    ax.add_patch(Circle((x, y), r, facecolor=color, edgecolor="none",
                        zorder=5))
    t = np.linspace(-1.6, 1.6, 60)
    ax.plot(x + t * 0.11, y + 0.16 + 0.05 * np.sin(2 * np.pi * t / 1.1),
            color=color, lw=1.2, zorder=5)


def qho_ladder():
    """One field mode = one harmonic oscillator: potential, levels, ladder."""
    fig, ax = plt.subplots(figsize=(7, 4.6))
    x = np.linspace(-3.1, 3.1, 300)
    ax.plot(x, 0.55 * x**2, color=INK, lw=2)

    for n in range(5):
        E = 0.5 + n
        xt = np.sqrt(2 * E / 1.1)
        ax.hlines(E, -xt, xt, color=ACCENT, lw=2)
        ax.text(xt + 0.15, E, rf"$|{n}\rangle$", va="center", fontsize=13,
                color=INK)
    ax.text(2.75, 4.85, r"$\vdots$", fontsize=15, color=INK)

    # ladder operators between |1> and |2>
    ax.annotate("", xy=(-1.15, 2.42), xytext=(-1.15, 1.58),
                arrowprops=dict(arrowstyle="-|>", color=GOOD, lw=2))
    ax.text(-1.05, 2.0, r"$\hat a^\dagger$", color=GOOD, fontsize=14)
    ax.annotate("", xy=(-1.75, 1.58), xytext=(-1.75, 2.42),
                arrowprops=dict(arrowstyle="-|>", color=HOT, lw=2))
    ax.text(-2.25, 2.0, r"$\hat a$", color=HOT, fontsize=14)

    # hbar omega spacing + zero point
    ax.annotate("", xy=(1.9, 3.5), xytext=(1.9, 2.5),
                arrowprops=dict(arrowstyle="<|-|>", color=INK, lw=1.4))
    ax.text(2.02, 3.0, r"$\hbar\omega$", fontsize=13, color=INK)
    ax.annotate("", xy=(0.0, 0.5), xytext=(0.0, 0.0),
                arrowprops=dict(arrowstyle="<|-|>", color=INK, lw=1.2))
    ax.text(0.1, 0.22, r"$\frac{1}{2}\hbar\omega$ zero point",
            fontsize=10, color=INK)

    ax.set_xlim(-3.3, 4.2)
    ax.set_ylim(-0.4, 5.4)
    ax.axis("off")
    ax.set_title("One field mode = one harmonic oscillator", fontsize=13)
    plt.tight_layout()
    plt.show()


def three_sources():
    """Laser / lamp / single emitter, with their photon streams."""
    fig, ax = _canvas(9.5, 4.4)

    # --- laser: box + collimated beam, evenly spaced photons
    ax.add_patch(Rectangle((0.2, 3.2), 1.3, 0.7, facecolor="#d9e6f2",
                           edgecolor=INK, lw=1.5))
    ax.text(0.85, 3.55, "laser", ha="center", va="center", fontsize=11)
    _beam(ax, 1.5, 3.55, 8.6, 3.55, color=ACCENT)
    for xp in np.linspace(2.4, 7.9, 6):
        _photon(ax, xp, 3.55, color=ACCENT)
    ax.text(8.9, 3.55, "coherent\nrandom, memoryless", fontsize=10,
            va="center", color=INK)

    # --- lamp: bulb + wiggly rays, clustered photons
    ax.add_patch(Circle((0.85, 2.0), 0.36, facecolor="#fbe8c9",
                        edgecolor=INK, lw=1.5))
    ax.add_patch(Rectangle((0.7, 1.5), 0.3, 0.22, facecolor="#e6e6e6",
                           edgecolor=INK, lw=1.2))
    ax.text(0.85, 2.0, "lamp", ha="center", va="center", fontsize=9)
    for ang in [35, 12, -25]:
        t = np.linspace(0, 1, 80)
        xr = 1.25 + 0.75 * t * np.cos(np.radians(ang))
        yr = 2.0 + 0.75 * t * np.sin(np.radians(ang)) \
            + 0.04 * np.sin(9 * np.pi * t)
        ax.plot(xr, yr, color=HOT, lw=1.2, alpha=0.7)
    _beam(ax, 1.35, 2.0, 8.6, 2.0, color=HOT)
    for xc in [2.9, 3.15, 3.32, 5.4, 5.62, 7.6, 7.78, 7.95]:
        _photon(ax, xc, 2.0, color=HOT)
    ax.text(8.9, 2.0, "thermal\nbunched, chaotic", fontsize=10,
            va="center", color=INK)

    # --- single emitter: two-level atom, one photon at a time
    ax.add_patch(Circle((0.85, 0.5), 0.3, facecolor="#dff2df",
                        edgecolor=INK, lw=1.5))
    ax.hlines(0.62, 0.72, 0.98, color=INK, lw=1.4)
    ax.hlines(0.38, 0.72, 0.98, color=INK, lw=1.4)
    ax.annotate("", xy=(0.85, 0.4), xytext=(0.85, 0.6),
                arrowprops=dict(arrowstyle="-|>", color=GOOD, lw=1.4))
    _beam(ax, 1.25, 0.5, 8.6, 0.5, color=GOOD)
    for xe in [3.0, 4.7, 6.4, 7.9]:
        _photon(ax, xe, 0.5, color=GOOD)
    ax.text(8.9, 0.5, "Fock-like\nantibunched, one at a time",
            fontsize=10, va="center", color=INK)

    ax.text(0.2, 4.25, "same average power — three different photon streams",
            fontsize=12, color=INK)
    ax.set_xlim(0, 11.6)
    ax.set_ylim(-0.2, 4.6)
    plt.tight_layout()
    plt.show()


def hbt_setup():
    """The Hanbury Brown-Twiss intensity interferometer."""
    fig, ax = _canvas(9.0, 4.2)

    ax.add_patch(Circle((0.7, 2.4), 0.32, facecolor="#fbe8c9",
                        edgecolor=INK, lw=1.5))
    ax.text(0.7, 2.4, "src", ha="center", va="center", fontsize=9)
    _beam(ax, 1.05, 2.4, 3.75, 2.4)
    _beamsplitter(ax, 4.0, 2.4, label="50:50")
    _beam(ax, 4.25, 2.4, 6.15, 2.4)                  # transmitted
    _detector(ax, 6.45, 2.4, angle=180, label="D1")
    _beam(ax, 4.0, 2.65, 4.0, 3.85)                  # reflected up
    _detector(ax, 4.0, 4.15, angle=270, label="D2")

    # correlator box + histogram inset
    ax.add_patch(Rectangle((6.9, 3.4), 1.9, 1.1, facecolor="#eee6f5",
                           edgecolor=INK, lw=1.5))
    ax.text(7.85, 4.28, "correlator", ha="center", fontsize=10, color=INK)
    tau = np.linspace(-1, 1, 60)
    ax.plot(7.0 + (tau + 1) * 0.85, 3.55 + 0.6 * (1 - np.exp(-np.abs(tau) / 0.25)),
            color=GOOD, lw=1.6)
    ax.text(7.85, 3.42, r"$g^{(2)}(\tau)$", ha="center", fontsize=9,
            color=GOOD, va="top")
    ax.plot([6.73, 6.9], [2.4, 3.7], color=INK, lw=1.1, ls=":")
    ax.plot([4.0, 6.9], [4.42, 4.2], color=INK, lw=1.1, ls=":")
    ax.text(6.73, 2.15, "start", fontsize=9, color=INK)
    ax.text(4.35, 4.42, "stop", fontsize=9, color=INK)

    ax.text(2.2, 2.62, "one beam", fontsize=9, color=INK)
    ax.text(4.55, 1.75,
            "dead time is per-detector —\nclose pairs land on different ones",
            fontsize=9, color=INK)
    ax.set_xlim(0, 9.4)
    ax.set_ylim(1.4, 4.8)
    plt.tight_layout()
    plt.show()


def hom_amplitudes():
    """The two indistinguishable two-photon processes that cancel."""
    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.6))
    for ax, (title, refl) in zip(
            axes, [("both transmitted:  amplitude $t \\cdot t$", False),
                   ("both reflected:  amplitude $r \\cdot r = (i/\\sqrt{2})^2$",
                    True)]):
        ax.set_aspect("equal")
        ax.axis("off")
        _beamsplitter(ax, 0, 0, size=0.7, label="")
        if not refl:
            _beam(ax, -1.6, 0.22, 1.6, 0.22, color=ACCENT)
            _beam(ax, -1.6, -0.22, 1.6, -0.22, color=HOT)
        else:
            _beam(ax, -1.6, 0.22, -0.05, 0.22, color=ACCENT, arrow=False)
            _beam(ax, -0.05, 0.22, -0.05, -1.5, color=ACCENT)
            _beam(ax, -1.6, -0.22, 0.05, -0.22, color=HOT, arrow=False)
            _beam(ax, 0.05, -0.22, 0.05, 1.5, color=HOT)
        _photon(ax, -1.25, 0.22, color=ACCENT)
        _photon(ax, -1.25, -0.22, color=HOT)
        ax.set_title(title, fontsize=11)
        ax.set_xlim(-1.9, 1.9)
        ax.set_ylim(-1.7, 1.7)
    fig.text(0.5, 0.06,
             "the two paths to a coincidence are indistinguishable "
             r"$\Rightarrow$ amplitudes add:  $t^2 + r^2 = "
             r"\frac{1}{2} - \frac{1}{2} = 0$",
             ha="center", fontsize=11.5)
    plt.subplots_adjust(bottom=0.2, top=0.9)
    plt.show()


def mzi_sketch():
    """Mach-Zehnder interferometer with a phase knob."""
    fig, ax = _canvas(8.6, 3.6)
    _beam(ax, 0.2, 0.6, 1.55, 0.6)
    _photon(ax, 0.75, 0.6, color=ACCENT)
    _beamsplitter(ax, 1.8, 0.6, label="BS$_1$")
    # mirrors at the two corners of the upper arm
    for xm in (1.8, 5.8):
        ax.plot([xm - 0.22, xm + 0.22], [2.42, 1.98], color=INK, lw=3.5,
                solid_capstyle="round", zorder=4)
    _beam(ax, 2.05, 0.6, 5.55, 0.6, color=ACCENT)        # lower arm
    _beam(ax, 1.8, 0.85, 1.8, 2.2, color=HOT)            # up
    _beam(ax, 1.8, 2.2, 5.8, 2.2, color=HOT)             # upper arm
    _beam(ax, 5.8, 2.2, 5.8, 0.85, color=HOT)            # down
    _beamsplitter(ax, 5.8, 0.6, label="BS$_2$")
    _beam(ax, 6.05, 0.6, 7.3, 0.6, color=INK)
    _detector(ax, 7.6, 0.6, angle=180, label="top")
    _beam(ax, 5.8, 0.35, 5.8, -0.55, color=INK)
    _detector(ax, 5.8, -0.85, angle=90, label="bottom")

    # the phase element in the upper arm
    ax.add_patch(Rectangle((3.4, 1.95), 0.6, 0.5, facecolor="#fbe8c9",
                           edgecolor=INK, lw=1.5, zorder=4))
    ax.text(3.7, 2.2, r"$\varphi$", ha="center", va="center", fontsize=13)
    ax.text(3.7, 2.62, "delay / phase", ha="center", fontsize=9, color=INK)

    ax.text(3.7, 0.32, "lower arm: no phase", fontsize=9, color=INK,
            ha="center")
    ax.set_xlim(0, 8.6)
    ax.set_ylim(-1.3, 3.0)
    plt.tight_layout()
    plt.show()


def spdc_heralding():
    """SPDC pair source with a heralding detector on the idler."""
    fig, ax = _canvas(9.2, 3.8)
    _beam(ax, 0.2, 1.8, 1.75, 1.8, color="#7b3fb3")
    ax.text(0.9, 2.05, "pump", fontsize=10, color="#7b3fb3")
    ax.add_patch(Polygon([(1.9, 1.35), (3.1, 1.35), (3.35, 2.25),
                          (2.15, 2.25)], closed=True, facecolor="#d9f2ee",
                         edgecolor=INK, lw=1.5))
    ax.text(2.62, 1.8, r"$\chi^{(2)}$", ha="center", va="center", fontsize=12)
    ax.text(2.62, 1.1, "nonlinear crystal", ha="center", fontsize=9,
            color=INK)

    # signal (down) and idler (up)
    _beam(ax, 3.25, 2.0, 6.9, 3.0, color=HOT)
    _photon(ax, 4.9, 2.53, color=HOT)
    ax.text(4.3, 3.05, "idler", fontsize=10, color=HOT)
    _detector(ax, 7.2, 3.1, angle=195, label="")
    ax.text(7.55, 3.45, "herald detector", fontsize=10, color=INK)

    _beam(ax, 3.25, 1.6, 6.9, 0.6, color=ACCENT)
    _photon(ax, 4.9, 1.07, color=ACCENT)
    ax.text(4.3, 0.5, "signal", fontsize=10, color=ACCENT)
    ax.add_patch(Rectangle((7.0, 0.25), 1.5, 0.7, facecolor="#dff2df",
                           edgecolor=INK, lw=1.5))
    ax.text(7.75, 0.6, r"$|1\rangle$ !", ha="center", va="center",
            fontsize=12, color=INK)

    # the herald signal (classical wire)
    ax.plot([7.25, 7.75, 7.75], [2.85, 2.0, 0.98], color=GOOD, lw=1.6,
            ls="--", zorder=1)
    ax.text(7.95, 1.9, "\"it's a pair —\nthe partner is here!\"",
            fontsize=9, color=GOOD)

    ax.text(0.25, 3.35, "pairs are born together: detecting one photon "
            "certifies its twin", fontsize=11, color=INK)
    ax.set_xlim(0, 9.6)
    ax.set_ylim(0, 3.7)
    plt.tight_layout()
    plt.show()


def ligo_noise_budget():
    """Schematic LIGO noise budget: who limits you at which frequency."""
    f = np.logspace(0.7, 3.5, 400)          # 5 Hz .. ~3 kHz

    seismic = 3e2 * (f / 10.0) ** -8        # the low-frequency wall
    thermal = 1.2 * (f / 100.0) ** -0.9     # suspension + coating Brownian
    rad_press = 2.0 * (f / 30.0) ** -2      # quantum back-action (amplitude quad.)
    shot = 0.35 * np.sqrt(1 + (f / 400.0) ** 2)   # shot noise (phase quad.)
    quantum = np.sqrt(rad_press ** 2 + shot ** 2)
    sql = 1.35 * (f / 55.0) ** -1           # standard quantum limit envelope
    total = np.sqrt(seismic ** 2 + thermal ** 2 + quantum ** 2)

    fig, ax = plt.subplots(figsize=(8, 4.8))
    ax.loglog(f, seismic, color="#8c6d31", lw=1.6, label="seismic wall")
    ax.loglog(f, thermal, color="#7b3fb3", lw=1.6, label="thermal (mirrors, fibers)")
    ax.loglog(f, rad_press, color=HOT, lw=1.6, ls="--",
              label="quantum: radiation pressure")
    ax.loglog(f, shot, color=ACCENT, lw=1.6, ls="--", label="quantum: shot noise")
    ax.loglog(f, sql, color=INK, lw=1.2, ls=":", label="standard quantum limit")
    ax.loglog(f, total, color="k", lw=2.6, alpha=0.75, label="total")

    # what squeezing does: press the shot-noise shoulder down
    ax.annotate("", xy=(1500, 0.55 * np.interp(1500, f, shot)),
                xytext=(1500, np.interp(1500, f, shot)),
                arrowprops=dict(arrowstyle="-|>", color=GOOD, lw=2.2))
    ax.text(1600, 0.42, "squeezed vacuum\npresses this down", color=GOOD,
            fontsize=9)

    ax.text(5.8, 0.16, "ground shakes:\nno laser can help", fontsize=8.5,
            color="#8c6d31")
    ax.text(60, 0.135, "same vacuum, two faces: amplitude quadrature pushes mirrors,\n"
            "phase quadrature blurs the fringe", fontsize=8.5, color=INK)

    ax.set_xlabel("frequency [Hz]")
    ax.set_ylabel("strain noise  [arb. units]")
    ax.set_title("Schematic interferometer noise budget (not to scale — "
                 "real ones: [Tse2019])")
    ax.set_ylim(0.08, 3e2)
    ax.legend(fontsize=8.5, loc="upper right", ncols=2)
    plt.tight_layout()
    plt.show()


def single_photon_bs():
    """One photon on a beamsplitter: the quantum coin (Grangier 1986)."""
    fig, ax = _canvas(8.0, 3.6)
    _beam(ax, 0.3, 1.2, 2.15, 1.2)
    _photon(ax, 1.1, 1.2, color=ACCENT)
    _beamsplitter(ax, 2.4, 1.2, label="50:50")
    _beam(ax, 2.65, 1.2, 4.4, 1.2, color=ACCENT, ls="--")
    _detector(ax, 4.7, 1.2, angle=180, label="D1")
    _beam(ax, 2.4, 1.45, 2.4, 2.9, color=ACCENT, ls="--")
    _detector(ax, 2.4, 3.2, angle=270, label="D2")
    ax.text(3.5, 1.45, "$P = 1/2$", fontsize=10, color=ACCENT)
    ax.text(2.55, 2.3, "$P = 1/2$", fontsize=10, color=ACCENT)
    # coincidence unit showing zero
    ax.add_patch(Rectangle((5.4, 2.4), 1.9, 0.9, facecolor="#eee6f5",
                           edgecolor=INK, lw=1.5))
    ax.text(6.35, 3.05, "coincidences", ha="center", fontsize=9, color=INK)
    ax.text(6.35, 2.7, "0  — never both", ha="center", fontsize=10,
            color=HOT)
    ax.plot([4.95, 5.4], [1.2, 2.6], color=INK, lw=1.1, ls=":")
    ax.plot([2.4, 5.4], [3.35, 3.1], color=INK, lw=1.1, ls=":")
    ax.text(0.3, 0.35,
            "each run: ONE click, D1 or D2, chosen at random — a quantum "
            "coin.\nNever both: a single photon does not split "
            "(Grangier–Roger–Aspect 1986).",
            fontsize=9.5, color=INK)
    ax.set_xlim(0, 8.0)
    ax.set_ylim(0, 3.7)
    plt.tight_layout()
    plt.show()


def hom_dip_setup():
    """The physical HOM experiment: pair source, delay stage, BS, dip."""
    fig, ax = _canvas(9.6, 4.4)
    # pump + crystal
    _beam(ax, 0.15, 2.2, 1.0, 2.2, color="#7b3fb3")
    ax.add_patch(Polygon([(1.1, 1.85), (1.95, 1.85), (2.15, 2.55),
                          (1.3, 2.55)], closed=True, facecolor="#d9f2ee",
                         edgecolor=INK, lw=1.5))
    ax.text(1.62, 2.2, r"$\chi^{(2)}$", ha="center", va="center",
            fontsize=11)
    # signal path (upper): crystal -> mirror -> down to BS
    _beam(ax, 2.05, 2.5, 4.3, 3.4, color=HOT, arrow=False)
    ax.plot([4.18, 4.62], [3.62, 3.28], color=INK, lw=3.5,
            solid_capstyle="round")            # mirror
    _beam(ax, 4.45, 3.35, 5.75, 2.45, color=HOT)
    _photon(ax, 3.2, 2.96, color=HOT)
    # idler path (lower) through the delay stage
    _beam(ax, 2.05, 1.9, 3.35, 1.35, color=ACCENT, arrow=False)
    ax.add_patch(Rectangle((3.4, 0.95), 1.15, 0.75, facecolor="#fbe8c9",
                           edgecolor=INK, lw=1.5))
    ax.text(3.97, 1.32, "delay", ha="center", va="center", fontsize=9)
    ax.annotate("", xy=(4.75, 0.72), xytext=(3.2, 0.72),
                arrowprops=dict(arrowstyle="<|-|>", color=INK, lw=1.3))
    ax.text(3.97, 0.45, r"$\pm\,\delta\tau$   (16 µm of travel = 100 fs!)",
            ha="center", fontsize=9, color=INK)
    _beam(ax, 4.55, 1.35, 5.75, 1.95, color=ACCENT)
    _photon(ax, 5.0, 1.6, color=ACCENT)
    # beamsplitter + detectors + coincidence
    _beamsplitter(ax, 6.0, 2.2, label="50:50")
    _beam(ax, 6.25, 2.2, 7.35, 2.2, color=INK)
    _detector(ax, 7.65, 2.2, angle=180, label="D1")
    _beam(ax, 6.0, 2.45, 6.0, 3.5, color=INK)
    _detector(ax, 6.0, 3.8, angle=270, label="D2")
    ax.add_patch(Rectangle((7.4, 3.15), 2.0, 1.15, facecolor="#eee6f5",
                           edgecolor=INK, lw=1.5))
    ax.text(8.4, 4.08, "coincidences", ha="center", fontsize=9, color=INK)
    # dip inset
    t = np.linspace(-1, 1, 80)
    ax.plot(7.55 + (t + 1) * 0.85, 3.45 + 0.5 * (1 - np.exp(-(t / 0.3) ** 2)),
            color=GOOD, lw=1.8)
    ax.text(8.4, 3.38, r"vs $\delta\tau$", ha="center", fontsize=8,
            color=GOOD, va="top")
    ax.plot([7.9, 7.6], [2.2, 3.35], color=INK, lw=1.1, ls=":")
    ax.plot([6.0, 7.4], [3.85, 3.9], color=INK, lw=1.1, ls=":")
    ax.text(0.15, 4.15, "scan the delay; when the wavepackets overlap\n"
            "at the beamsplitter, coincidences vanish: the HOM dip",
            fontsize=9.5, color=INK, va="top")
    ax.set_xlim(0, 9.8)
    ax.set_ylim(0.2, 4.4)
    plt.tight_layout()
    plt.show()


def noon_mzi():
    """The NOON interferometer: HOM makes the state, phase counts double."""
    fig, ax = _canvas(9.2, 3.9)
    _beam(ax, 0.2, 0.85, 1.5, 0.85)
    _photon(ax, 0.8, 0.85, color=ACCENT)
    _beam(ax, 1.75, -0.05, 1.75, 0.55, color=HOT)
    _photon(ax, 1.75, 0.15, color=HOT)
    _beamsplitter(ax, 1.75, 0.85, label="")
    ax.text(1.15, 0.52, "BS$_1$", fontsize=10, color=INK)
    for xm in (1.75, 5.9):
        ax.plot([xm - 0.22, xm + 0.22], [2.62, 2.18], color=INK, lw=3.5,
                solid_capstyle="round", zorder=4)
    _beam(ax, 1.75, 1.1, 1.75, 2.4, color="#7b3fb3")
    _beam(ax, 1.75, 2.4, 5.9, 2.4, color="#7b3fb3")
    _beam(ax, 5.9, 2.4, 5.9, 1.1, color="#7b3fb3")
    _beam(ax, 2.0, 0.85, 5.65, 0.85, color="#7b3fb3")
    _beamsplitter(ax, 5.9, 0.85, label="BS$_2$")
    _beam(ax, 6.15, 0.85, 7.2, 0.85, color=INK)
    _detector(ax, 7.5, 0.85, angle=180, label="")
    _beam(ax, 5.9, 0.6, 5.9, -0.3, color=INK)
    _detector(ax, 5.9, -0.6, angle=90, label="")
    # phase element
    ax.add_patch(Rectangle((3.5, 2.15), 0.6, 0.5, facecolor="#fbe8c9",
                           edgecolor=INK, lw=1.5, zorder=4))
    ax.text(3.8, 2.4, r"$\varphi$", ha="center", va="center", fontsize=13,
            zorder=5)
    # state annotations
    ax.text(2.35, 1.55, r"HOM at BS$_1$ makes the NOON state:", fontsize=10,
            color="#7b3fb3")
    ax.text(2.35, 1.22,
            r"$\left(|2,0\rangle - |0,2\rangle\right)/\sqrt{2}$",
            fontsize=12, color="#7b3fb3")
    ax.text(2.0, 3.0, r"$|2,0\rangle \to e^{i2\varphi}\,|2,0\rangle$: the pair pays the phase twice", fontsize=10, color=INK)
    # inset: cos(2phi) fringe vs single-photon fringe
    ax.add_patch(Rectangle((7.15, 1.8), 2.0, 1.5, facecolor="white",
                           edgecolor=INK, lw=1.2))
    ph = np.linspace(0, 2 * np.pi, 120)
    ax.plot(7.25 + ph / (2 * np.pi) * 1.8, 2.55 + 0.6 * 0.5 * np.cos(2 * ph),
            color="tab:purple", lw=1.8)
    ax.plot(7.25 + ph / (2 * np.pi) * 1.8, 2.55 + 0.6 * 0.5 * np.cos(ph),
            color="gray", lw=1.0, ls="--")
    ax.text(8.15, 1.92, r"coinc. $\propto \cos 2\varphi$", ha="center",
            fontsize=8.5, color="tab:purple")
    ax.set_xlim(0, 9.4)
    ax.set_ylim(-1.0, 3.4)
    plt.tight_layout()
    plt.show()


def stellar_hbt():
    """Stellar intensity interferometry: correlate intensities, not fields."""
    fig, ax = _canvas(9.6, 5.2)

    # the star, with (exaggerated) angular size
    ax.add_patch(Circle((4.8, 4.55), 0.28, facecolor="#fbe8c9",
                        edgecolor=INK, lw=1.5))
    for ang in np.linspace(0, 2 * np.pi, 8, endpoint=False):
        ax.plot([4.8 + 0.33 * np.cos(ang), 4.8 + 0.48 * np.cos(ang)],
                [4.55 + 0.33 * np.sin(ang), 4.55 + 0.48 * np.sin(ang)],
                color="#c9962e", lw=1.4)
    ax.annotate("", xy=(4.1, 4.9), xytext=(5.5, 4.9),
                arrowprops=dict(arrowstyle="<|-|>", color=INK, lw=1.1))
    ax.text(4.8, 5.05, r"angular size $\theta$", ha="center", fontsize=9,
            color=INK)

    # light cones to the two telescopes
    for xt in (2.3, 7.3):
        ax.plot([4.55, xt - 0.35], [4.4, 1.75], color="#c9962e", lw=1.0,
                alpha=0.65)
        ax.plot([5.05, xt + 0.35], [4.4, 1.75], color="#c9962e", lw=1.0,
                alpha=0.65)

    # telescopes: dish + mount, detector at focus
    for xt in (2.3, 7.3):
        ax.add_patch(Polygon([(xt - 0.55, 1.75), (xt + 0.55, 1.75),
                              (xt, 1.35)], closed=True,
                             facecolor="#d9e6f2", edgecolor=INK, lw=1.5))
        ax.plot([xt, xt], [1.35, 0.95], color=INK, lw=2.5)
        _detector(ax, xt, 1.62, angle=90, label="")
    ax.text(2.3, 0.72, "telescope 1", ha="center", fontsize=9, color=INK)
    ax.text(7.3, 0.72, "telescope 2", ha="center", fontsize=9, color=INK)

    # baseline
    ax.annotate("", xy=(2.3, 0.42), xytext=(7.3, 0.42),
                arrowprops=dict(arrowstyle="<|-|>", color=INK, lw=1.3))
    ax.text(4.8, 0.18, "baseline $d$  (movable — no phase stability needed)",
            ha="center", fontsize=9.5, color=INK)

    # the 'flickers together' traces beside each telescope
    t = np.linspace(0, 1, 160)
    rng = np.random.default_rng(3)
    base = np.convolve(rng.normal(size=220), np.ones(25) / 25,
                       mode="same")[30:190]
    for xt, sign in ((0.55, 1), (8.05, 1)):
        ax.plot(xt + t * 1.15, 2.65 + 1.6 * base, color=HOT, lw=1.2)
        ax.text(xt + 0.57, 3.35, "$I(t)$", ha="center", fontsize=9,
                color=HOT)
    ax.text(4.8, 2.5, "close detectors: the thermal light\n"
            '"flickers together"', ha="center", fontsize=9.5, color=HOT)

    # cables to the multiplier / correlator
    ax.plot([2.3, 2.3, 4.45], [0.95, 0.9, 0.9], color=INK, lw=1.4)
    ax.plot([7.3, 7.3, 5.15], [0.95, 0.9, 0.9], color=INK, lw=1.4)
    ax.add_patch(Circle((4.8, 0.9), 0.22, facecolor="#eee6f5",
                        edgecolor=INK, lw=1.5, zorder=4))
    ax.text(4.8, 0.9, r"$\times$", ha="center", va="center", fontsize=13,
            zorder=5)
    ax.text(4.8, 1.28, r"multiply & average:  $\langle I_1 I_2\rangle$",
            ha="center", fontsize=9, color=INK)

    # inset: correlation vs baseline
    ax.add_patch(Rectangle((0.25, 3.95), 2.3, 1.25, facecolor="white",
                           edgecolor=INK, lw=1.2))
    d = np.linspace(0, 1, 80)
    ax.plot(0.4 + d * 2.0, 4.15 + 0.85 * np.exp(-(d / 0.35) ** 2),
            color=GOOD, lw=1.8)
    ax.text(1.4, 4.02, r"$g^{(2)}(d)-1$  dies at  $d \sim \lambda/\theta$",
            ha="center", fontsize=8, color=GOOD, va="top")
    ax.set_xlim(0, 9.6)
    ax.set_ylim(0, 5.3)
    plt.tight_layout()
    plt.show()
